import { LocationData } from "@/features/weather/models"

export const mock = [
  {
    id: "2801268",
    name: "London, City of London, Greater London, United Kingdom",
    region: "City of London, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.11,
    url: "london-city-of-london-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2796590",
    name: "Holborn, Camden, Greater London, United Kingdom",
    region: "Camden, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.12,
    url: "holborn-camden-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2812957",
    name: "St Giles, Camden, Greater London, United Kingdom",
    region: "Camden, Greater London",
    country: "United Kingdom",
    lat: 51.52,
    lon: -0.12,
    url: "st-giles-camden-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2786308",
    name: "Clerkenwell, Islington, Greater London, United Kingdom",
    region: "Islington, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.11,
    url: "clerkenwell-islington-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2791655",
    name: "Finsbury, Islington, Greater London, United Kingdom",
    region: "Islington, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.11,
    url: "finsbury-islington-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2813087",
    name: "St Pancras, Camden, Greater London, United Kingdom",
    region: "Camden, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.12,
    url: "st-pancras-camden-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2781746",
    name: "Bloomsbury, Camden, Greater London, United Kingdom",
    region: "Camden, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.12,
    url: "bloomsbury-camden-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2813948",
    name: "Strand, Westminster, Greater London, United Kingdom",
    region: "Westminster, Greater London",
    country: "United Kingdom",
    lat: 51.51,
    lon: -0.12,
    url: "strand-westminster-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2811665",
    name: "Shoreditch, Hackney, Greater London, United Kingdom",
    region: "Hackney, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.09,
    url: "shoreditch-hackney-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
  {
    id: "2813028",
    name: "St Luke's, Islington, Greater London, United Kingdom",
    region: "Islington, Greater London",
    country: "United Kingdom",
    lat: 51.53,
    lon: -0.09,
    url: "st-lukes-islington-greater-london-united-kingdom",
    tz_id: "Asia/Tokyo",
    localtime_epoch: 1726101181,
    localtime: "2024-09-30 09:33",
  },
] satisfies LocationData
